version: '3.8'

services:
  go-app:
    build: ./go-app
    container_name: go-app
    ports:
      - "8080:8080"

  nextjs-app:
    build: ./nextjs-app
    container_name: nextjs-app
    ports:
      - "3000:3000"

  wordpress:
    build: ./wordpress-site
    container_name: wordpress
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
